### ISSUE TITLE
Add Navigation to Processbook

### ISSUE THREAD

**Issue by danieljsmarda** [mbovel/dataviz-project#28]
At time of creating this issue I am still working on the main content of the process book. When the content is complete I will submit a pull request. At that time, when you can see the content, anyone else is welcome to add the nav part, or I can (though I would like confirmation on the best structure before I dive into that because I'm still learning Jekyll and I want to make sure I don't mess up our currently very-neat framework).

**Comment by mbovel** [comment]
Done in 1a1d097b25742658e45166023d5b287b024628e3 😃
