### ISSUE TITLE
Make "click here to view viz" open in new tab

### ISSUE THREAD

**Issue by danieljsmarda** [mbovel/dataviz-project#36]
I'm sure this is a simple fix using a line like the following:
```html
<a href="http://example.com/" target="_blank">Hello, world!</a>
```
I think the solution is just to replace the corresponding line in `index.md`. I would do it myself now but since I don't have Jekyll I'm afraid to put something that affects navigation without testing it first.

**Comment by mbovel** [comment]
It's considered a bad practice to force opening a link in a new tab. See https://medium.com/the-metric/links-should-open-in-the-same-window-447da3ae59ba for example.
